# Generated by Django 6.1 on 2026-09-19 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feecategory',
            options={'ordering': ['name']},
        ),
    ]
