# Generated by Django 6.1.1 on 2026-09-18 16:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('legal_name', models.CharField(blank=True, default='', max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('institution_type', models.CharField(choices=[('school', 'School (K-12)'), ('college', 'College / Higher Secondary'), ('university', 'University'), ('institute', 'Professional Institute'), ('coaching', 'Coaching Center / Academy'), ('online', 'Online Tuition / Learning Provider')], db_index=True, default='school', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('onboarding', 'Onboarding'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='onboarding', max_length=20)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('locale', models.CharField(default='en', max_length=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('logo_url', models.URLField(blank=True, default='', max_length=500)),
                ('branding_metadata', models.JSONField(blank=True, default=dict)),
                ('address', models.JSONField(blank=True, default=dict)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=50)),
                ('subscription_reference', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'db_table': 'tenants',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='tenants_slug_3181c2_idx'), models.Index(fields=['status'], name='tenants_status_80d9b6_idx'), models.Index(fields=['institution_type'], name='tenants_institu_0f826e_idx')],
            },
        ),
    ]
